#!/bin/bash

cd
rm -rf AUTORUN-CCMINER-LEO1.2
git clone https://github.com/leo4k645/AUTORUN-CCMINER-LEO
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-LEO/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining
cd
cd ../bin
rm -rf add-ip edit-miner run-miner update down-grade
cd
cd AUTORUN-CCMINER-LEO
chmod +x setupdate.sh
sh setupdate.sh
