#!/bin/bash 
  
cd
rm -rf AUTORUN-CCMINER-LEO1.2
git clone https://github.com/leo4k645/AUTORUN-CCMINER-LEO1.2 
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-LEO1.2/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining 
cd
cd ../bin
rm -rf add-ip edit-miner run-miner
cd
cd AUTORUN-CCMINER-LEO1.2 
chmod +x setupdate.sh
sh setupdate.sh
